### ISSUE TITLE
The dGPU temperature reported by the Python version might not be correct

### ISSUE THREAD

**Issue by PlankCipher** [DavidLapous/DellG5SE-Fan-Linux#9]
I ran `watch -n 1 cat /sys/class/drm/card0/device/hwmon/hwmon*/temp1_input` as mentioned in the [ArchWiki AMDGPU](https://wiki.archlinux.org/title/AMDGPU#Monitoring) page to monitor the dGPU temperature. Then, I threw some heavy load on the dGPU prefixing the commands with `DRI_PRIME=1` to make sure they run on the dGPU. And indeed `radeontop` indicated increased load on the dGPU, and the `watch` command indicated increased temperature to about `57 C` but the Python version didn't respond to the increase of temperature as it reported the temperature to be `53 C` (I have the lowtemp option set to `55` in the config file).

**Comment by PlankCipher** [comment]
Somehow it is working correctly now.

**Comment by DavidLapous** [comment]
The python scripts does not use these sensors to get dgpu temps, it uses temps provided by dell_smm (see lines 95-107 and 145). My reasons to do that :
1. You're not cooling directly cpu and dgpu but the heatsink under it, it is useless to trigger fans if the heatsinks are at room temperature, not matter what temp is the dgpu/cpu. Furthermore,  taking as sensors the hot spot of dgpu / cpu for fan curve would yield a very erratic fan speed & noise, as this can go from 40 to 90 to 40 in some seconds. 
2. By default, the laptop uses the dellsmm sensors to trigger the fans, it (almost surely) take into account the other components the laptop such as memory, sdd ... I've already seen this sensor being higher than the hotspot of cpu/dpgu. 
3. Asking for temps of dgpu through amdgpu (and not from dell's dellsmm sensor) wakes up the dgpu from sleep state. There are freezes issues on this laptop regarding that, so its preferable not to freeze the laptop / prevent dgpu to sleep by not using this sensor.

I've a small question, I don't see any advantage to use the python version, why are you using this instead of the c version (which has a much smaller footprint in ram, and has better fan control) ?

**Comment by PlankCipher** [comment]
Thanks for the clarification. I am using both the `C` and the `Python` versions to ease making keybindings for my rice.
